@Rydo_Api_HostAddress = http://localhost:5190

GET {{Rydo_Api_HostAddress}}/health/live

###

GET {{Rydo_Api_HostAddress}}/api/v1/system
Accept: application/json

###

POST {{Rydo_Api_HostAddress}}/api/v1/auth/otp/request
Content-Type: application/json

{
  "phoneNumber": "+27820000000",
  "role": "Passenger"
}

###
